[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "docker-quality-analyzer-backend"
version = "0.1.0"
description = "Backend for Docker Quality Analyzer"
requires-python = ">=3.12"
dependencies = []

[tool.setuptools.packages.find]
where = ["."]
include = ["app*"]
